# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
facebook_username:
linkedin_username:
email_username:

# Build settings
markdown: kramdown
